# Generated by Django 3.1.7 on 2021-02-25 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='leave_balances',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
