# Generated by Django 3.0.11 on 2021-02-28 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210225_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='leave_balances',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
