# Generated by Django 3.0.11 on 2021-02-28 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210228_1531'),
        ('leaverequests', '0002_auto_20210225_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leaverequest', to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
